language: go

sudo: false

services:
    - docker

go:
    - 1.8.x
    - tip

before_install:
    - mkdir -p $HOME/bin
    - curl -s https://raw.githubusercontent.com/sagikazarmark/traviscripts/e106b6d593915a0cb736919ecb3804e8eb5e0440/scripts/glide.sh | bash
    - make envcheck

install: make setup

before_script:
    - export VERSION=${TRAVIS_TAG:-$TRAVIS_BRANCH}
    - export DOCKER_IMAGE=deshboard/$(go list . | cut -d '/' -f 3)

script:
    - make ARGS="-tags=integration" check
    - if [[ $TRAVIS_EVENT_TYPE = push ]]; then make IMAGE=$DOCKER_IMAGE VERSION=$VERSION docker; fi

deploy:
    provider: script
    skip_cleanup: true
    script: docker login -u $DOCKER_USER -p $DOCKER_PASS && docker push $DOCKER_IMAGE
    on:
        all_branches: true
        condition: $TRAVIS_GO_VERSION =~ ^1\.8(\.[0-9]+)?$
